spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/eventostec
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

aws.region=us-east-1
aws.bucket.name=eventostec-imagens93